package ht.wt.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import ht.wt.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.20 08:49:12 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class PaivaTest {


  // Generated by ComTest BEGIN
  /** testToString43 */
  @Test
  public void testToString43() {    // Paiva: 43
    Paiva paiva = new Paiva(); 
    paiva.parse("    12.3.2020   |   Orivesi       |  07:18"); 
    assertEquals("From: Paiva line: 46", true, paiva.toString().startsWith("12.3.2020|Orivesi|07:18|")); 
  } // Generated by ComTest END
}