package ht.wt.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import ht.wt.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.20 09:43:22 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class PaivatTest {



  // Generated by ComTest BEGIN
  /** testLisaa72 */
  @Test
  public void testLisaa72() {    // Paivat: 72
    Paivat paivat = new Paivat(); 
    Paiva pvm = new Paiva(), pvm1 = new Paiva(); 
    assertEquals("From: Paivat line: 75", 0, paivat.getLkm()); 
    paivat.lisaa(pvm1); assertEquals("From: Paivat line: 76", 1, paivat.getLkm()); 
    paivat.lisaa(pvm); assertEquals("From: Paivat line: 77", 2, paivat.getLkm()); 
    paivat.lisaa(pvm1); assertEquals("From: Paivat line: 78", 3, paivat.getLkm()); 
    assertEquals("From: Paivat line: 79", pvm1, paivat.anna(0)); 
    assertEquals("From: Paivat line: 80", pvm, paivat.anna(1)); 
    assertEquals("From: Paivat line: 81", pvm1, paivat.anna(2)); 
    assertEquals("From: Paivat line: 82", false, paivat.anna(1) == pvm1); 
    assertEquals("From: Paivat line: 83", true, paivat.anna(1) == pvm); 
    try {
    assertEquals("From: Paivat line: 84", pvm, paivat.anna(3)); 
    fail("Paivat: 84 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    paivat.lisaa(pvm1); assertEquals("From: Paivat line: 85", 4, paivat.getLkm()); 
    paivat.lisaa(pvm1); assertEquals("From: Paivat line: 86", 5, paivat.getLkm()); 
    paivat.lisaa(pvm1); assertEquals("From: Paivat line: 87", 6, paivat.getLkm()); 
  } // Generated by ComTest END
}