package ht.wt.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import ht.wt.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.18 15:03:33 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class PaivatTest {



  // Generated by ComTest BEGIN
  /** testLisaa58 */
  @Test
  public void testLisaa58() {    // Paivat: 58
    Paivat paivat = new Paivat(); 
    Paiva pvm = new Paiva(), pvm1 = new Paiva(); 
    assertEquals("From: Paivat line: 61", 0, paivat.getLkm()); 
    paivat.lisaa(pvm1); assertEquals("From: Paivat line: 62", 1, paivat.getLkm()); 
    paivat.lisaa(pvm); assertEquals("From: Paivat line: 63", 2, paivat.getLkm()); 
    paivat.lisaa(pvm1); assertEquals("From: Paivat line: 64", 3, paivat.getLkm()); 
    assertEquals("From: Paivat line: 65", pvm1, paivat.anna(0)); 
    assertEquals("From: Paivat line: 66", pvm, paivat.anna(1)); 
    assertEquals("From: Paivat line: 67", pvm1, paivat.anna(2)); 
    assertEquals("From: Paivat line: 68", false, paivat.anna(1) == pvm1); 
    assertEquals("From: Paivat line: 69", true, paivat.anna(1) == pvm); 
    try {
    assertEquals("From: Paivat line: 70", pvm, paivat.anna(3)); 
    fail("Paivat: 70 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    paivat.lisaa(pvm1); assertEquals("From: Paivat line: 71", 4, paivat.getLkm()); 
    paivat.lisaa(pvm1); assertEquals("From: Paivat line: 72", 5, paivat.getLkm()); 
    paivat.lisaa(pvm1); assertEquals("From: Paivat line: 73", 6, paivat.getLkm()); 
  } // Generated by ComTest END
}