package ht.wt.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import ht.wt.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.18 15:05:13 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class WeatherTrackerTest {



  // Generated by ComTest BEGIN
  /** testLisaa49 */
  @Test
  public void testLisaa49() {    // WeatherTracker: 49
    WeatherTracker weathertracker = new WeatherTracker(); 
    Paiva pvm = new Paiva(), pvm1 = new Paiva(); 
    assertEquals("From: WeatherTracker line: 52", 0, weathertracker.getPaivat()); 
    weathertracker.lisaa(pvm1); assertEquals("From: WeatherTracker line: 53", 1, weathertracker.getPaivat()); 
    weathertracker.lisaa(pvm); assertEquals("From: WeatherTracker line: 54", 2, weathertracker.getPaivat()); 
    weathertracker.lisaa(pvm1); assertEquals("From: WeatherTracker line: 55", 3, weathertracker.getPaivat()); 
    assertEquals("From: WeatherTracker line: 56", pvm1, weathertracker.annaPaiva(0)); 
    assertEquals("From: WeatherTracker line: 57", pvm, weathertracker.annaPaiva(1)); 
    assertEquals("From: WeatherTracker line: 58", pvm1, weathertracker.annaPaiva(2)); 
    try {
    assertEquals("From: WeatherTracker line: 59", pvm, weathertracker.annaPaiva(3)); 
    fail("WeatherTracker: 59 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    weathertracker.lisaa(pvm1); assertEquals("From: WeatherTracker line: 60", 4, weathertracker.getPaivat()); 
    weathertracker.lisaa(pvm1); assertEquals("From: WeatherTracker line: 61", 5, weathertracker.getPaivat()); 
    weathertracker.lisaa(pvm1); assertEquals("From: WeatherTracker line: 62", 6, weathertracker.getPaivat()); 
  } // Generated by ComTest END
}